apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-app-deployment
  labels:
    app: maven-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maven-app
  template:
    metadata:
      labels:
        app: maven-app
    spec:
      containers:
        - name: maven-app-container
          image: abdelmonimmoumay059/my-repo:${IMAGE_TAG} # Variable à remplacer dans le pipeline Jenkins
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: maven-app-service
spec:
  selector:
    app: maven-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
