apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-app-deployment
  labels:
    app: maven-app
spec:
  replicas: 3  # Nombre de pods à créer
  selector:
    matchLabels:
      app: maven-app
  template:
    metadata:
      labels:
        app: maven-app
    spec:
      containers:
        - name: maven-app-container
          image: your-docker-image:latest  # Remplacez par l'image de votre application Maven
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: maven-app-service
  labels:
    app: maven-app
spec:
  selector:
    app: maven-app  # Correspond aux labels dans le Deployment
  ports:
    - protocol: TCP
      port: 80          # Port exposé par le service
      targetPort: 8080  # Port utilisé par les conteneurs
  type: LoadBalancer    # Expose l'application à l'extérieur
