apiVersion: apps/v1
kind: Deployment
metadata:
  name: Maven-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maven-app
  template:
    metadata:
      labels:
        app: maven-app
    spec:
      containers:
        - name: maven-app
          image:  abdelmonimmoumay059/my-repo:latest
          ports:
            - containerPort: 8080
